<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="priyankas-MacBook-Pro.local" failures="2" tests="3" name="Nopackage" time="53.374" errors="0" timestamp="05 Jul 2020 17:02:29 GMT">
  <testcase classname="testCases.CheckoutFlowTest" name="goTillCheckout" time="33.152"/>
  <testcase classname="testCases.CheckoutFlowTest" name="checkoutFlowTest" time="7.268">
    <failure type="java.lang.AssertionError" message="FAILED expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: FAILED expected [true] but found [false]
at testCases.CheckoutFlowTest.checkoutFlowTest(CheckoutFlowTest.java:65)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 49 stack frames]]>
    </failure>
  </testcase> <!-- checkoutFlowTest -->
  <testcase classname="testCases.CheckoutFlowTest" name="checkoutFlowTest" time="7.022">
    <failure type="java.lang.AssertionError" message="FAILED expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: FAILED expected [true] but found [false]
at testCases.CheckoutFlowTest.checkoutFlowTest(CheckoutFlowTest.java:65)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 49 stack frames]]>
    </failure>
  </testcase> <!-- checkoutFlowTest -->
</testsuite> <!-- Nopackage -->
